### ISSUE TITLE
Unable to get booleans to be assigned correctly

### ISSUE THREAD

**Issue by drgeb** [oravirt/ansible-oracle-modules#1]
Hi,
I can run the code fine but all booleans are not properly send across.
So I keep running into this error:
failed: [default] => (item={u'datafile': u'/u02/oradata/retail/centraloffice/tbs_01.dbf', u'name': u'centralofficedb', u'autoextend': u'yes', u'state': u'present', u'next': u'5M', u'content': u'permanent', u'maxsize': u'500M', u'size': u'100M'}) => {"failed": true, "item": {"autoextend": "yes", "content": "permanent", "datafile": "/u02/oradata/retail/centraloffice/tbs_01.dbf", "maxsize": "500M", "name": "centralofficedb", "next": "5M", "size": "100M", "state": "present"}, "msg": "value of autoextend must be one of: yes,on,1,true,1,no,off,0,false,0, got: yes "}

So here on purpose I set the value in the yml to yes and it still says autoextend is not set but it got value yes.

So somehow its not converting, i have had this this issue also with big file and using the test.yml.

Any ideas? 
Thanks

**Comment by oravirt** [comment]
Hi,

Try using true/false instead of yes/no and see if that makes a difference. I'll have to look into the code to see how that part is handled.

Thanks
/M

**Comment by drgeb** [comment]
I have tried all the combinations did not work for me. So I decided to create a simple module and test and got the same response. So it did not convert it to bool. Enclosed is the test code, yml file and response I got on my machine in verbose mode.
Only thing I can think of is that there is an issue with the versions of python and ansible I am using??


[Archive.zip](https://github.com/oravirt/ansible-oracle-modules/files/212504/Archive.zip)

**Comment by oravirt** [comment]
Yeah I got the same error now. 
As a workaround, try quoting true/false in lower-case, i.e "true". That should work

I need to fix this.

Thanks for bringing this up!

**Comment by oravirt** [comment]
Hi,

This commit, 2fc4c02e82b27354a5ef94184a0fdf84446fa74b should fix the issue.

Thanks.
/M

**Comment by drgeb** [comment]
Hi oravirt, 
I was just looking at this also and saw you checked in new code!
What I found out on this end is http://docs.ansible.com/ansible/developing_modules.html
Modules accepting boolean status should generally accept ‘yes’, ‘no’, ‘true’, ‘false’, or anything else a user may likely throw at them. The AnsibleModule common code supports this with “type=’bool’”.

so I was trying to test out the following changes:
bigfile       = dict(default=False, choices=BOOLEANS,type='bool'),
autoextend    = dict(default=False, choices=BOOLEANS,type='bool'),

will send an update for the new tests of your code! Thanks

**Comment by oravirt** [comment]
Hi,

Yeah, just tried it it works. So I'm going to change this again with the proper fix (type=bool).
It helps to read the documentation ;-)

**Comment by oravirt** [comment]
I may have spoken prematurely. I'll leave this for tomorrow, to tired now.

**Comment by drgeb** [comment]
I am swamped with work also! Will let you know on what I find!
