### ISSUE TITLE
oracle_ldapuser: Does the module work with 10, 11 and 12 Oracle DB versions?

### ISSUE THREAD

**Issue by luismanuu** [oravirt/ansible-oracle-modules#105]
I have several databases with different versions (10, 11 and 12). Will the sync  work in every version?

**Comment by oravirt** [comment]
@ilmarkerm ?

**Comment by ilmarkerm** [comment]
I'm quite sure about 11 and 12. But I can't really think now why it shouldn't work on 10.2 either.

**Comment by luismanuu** [comment]
Thanks
