### ISSUE TITLE
Please submit upstream

### ISSUE THREAD

**Issue by liquidat** [oravirt/ansible-oracle-modules#12]
This is a great set of modules, and I am afraid that many people who really need that are not aware of this repository.
I suggest that you submit these upstream so that it reaches a much broader audience.

**Comment by oravirt** [comment]
Thank you!

I fully intend to do that. 
However, there are a number of things that needs to be fixed first and I just don't have the time at the moment.

**Comment by liquidat** [comment]
Closing after a few years, is probably not gonna happen.
