### ISSUE TITLE
Question about oracle_profile

### ISSUE THREAD

**Issue by anandsolomon** [oravirt/ansible-oracle-modules#129]
Can I create multiple profile with the same attributes ? Some this like this

    profiles:
            - name:
               - profile1
               - profile2

**Comment by oravirt** [comment]
If you don't want to repeat the attributes for each profile, I would put the attributes for the profiles in it's own variable (like a 'common/shared' attributes variable) and reference that variable when managing the profiles

**Comment by anandsolomon** [comment]
Nice, this worked. !!!
