### ISSUE TITLE
ERROR! 'with_item' is not a valid attribute for a Task in oracle_sql

### ISSUE THREAD

**Issue by anandsolomon** [oravirt/ansible-oracle-modules#132]
I am trying to use with_item to read the sql from a file.

    - name: Script will revoke grants from certain user for complaince in AWS RDS
      oracle_sql:
        username: "{{user}}"
        password: "{{password}}"
        service_name: "{{sname}}"
        port: "{{prt}}"
        hostname: "{{hostname}}"
        sql: "{{ item }}"
      with_item: "{{ sqls }}"
      environment: "{{oracle_env}}"
      register: query_result
      connection: local

I am getting ERROR! 'with_item' is not a valid attribute for a Task. Is this supported in oracle_sql module.

**Comment by oravirt** [comment]
`with_items:`
You’re missing a ‘s’

**Comment by anandsolomon** [comment]
Thanks !!!
