### ISSUE TITLE
oracle_user question 

### ISSUE THREAD

**Issue by anandsolomon** [oravirt/ansible-oracle-modules#136]
Can i create user with privileges like ADMIN OPTION

GRANT ALTER DATABASE LINK TO USERNAME WITH ADMIN OPTION;
GRANT ALTER PUBLIC DATABASE LINK TO USERNAME WITH ADMIN OPTION;

**Comment by oravirt** [comment]
Hi,

This would probably fall under `oracle_grants`, but no, `admin option` Is not supported right now.

**Comment by anandsolomon** [comment]
Thanks
