### ISSUE TITLE
Oracle Parameter

### ISSUE THREAD

**Issue by sathishbbala** [oravirt/ansible-oracle-modules#137]
Can someone please help me understand why I am needed to change the following code?

    elif name.startswith('_') and mode == 'sysdba':
        sql = 'select **count(*)** from sys.x$ksppi where ksppinm = lower(\'%s\')' % name

    else:
        sql = 'select **count(*)** from v$parameter where name = lower(\'%s\')' % name

    try:
            cursor.execute(sql)
            result = (cursor.fetchone())
    except cx_Oracle.DatabaseError as exc:
            error, = exc.args
            msg = error.message+ 'sql: ' + sql
            return False

    **if result is None:
        msg = 'The parameter (%s) doesn\'t exist' % name
        return False
    else:
        return True**

**Comment by oravirt** [comment]
What is the problem you're trying to solve?

**Comment by sathishbbala** [comment]
Here is my code: 

---
 - hosts: localhost
   user: oracle
   gather_facts: false

   vars:
      ansible_python_interpreter: /bin/python3
      oracle_home:
      oraclehost: 
      oracleport: 
      oracleservice: 
      oracleuser: sys
      oraclepassword: 
      oraclemode: sysdba
      oracle_env:
            ORACLE_HOME: "{{ oracle_home }}"
            LD_LIBRARY_PATH: "{{ oracle_home }}"

      cdb_common_parameters:
           - { name: awr_pdb_autoflush_enabled, value: TRUE }

   tasks:

     - debug:
         msg: "{{ hostvars['localhost']['ansible_python_interpreter'] }}"

     - name: set parameter
       oracle_parameter: hostname={{ oraclehost }} port={{ oracleport }} service_name={{ oracleservice }} user={{ oracleuser }} mode={{ oraclemode }} password={{ oraclepassword }} name={{ item.name }} value={{ item.value }} state=present scope=spfile sid='*'
       with_items: "{{ cdb_common_parameters }}"

I ran into an error with this piece of code earlier but not now. Not sure what changed.

**Comment by oravirt** [comment]
Ok, so it’s not a problem anymore?

**Comment by sathishbbala** [comment]
No, no errors now
