### ISSUE TITLE
oracle_user: wanted_list and curr_defaults are not compared case insensitive

### ISSUE THREAD

**Issue by jschampera** [oravirt/ansible-oracle-modules#162]
While debugging why a given user was changed on every run, I took a look into oracle_user.

wanted_list and curr_defaults are not compared case-insensitive (where applicable, e.g. tablespace names).

My current workaround is to use lowercase tablespace names in the yaml files, but it should be corrected.

(probably other modules are affected aswell, I didn't check/I'm not that far in my adventure :-) )

**Comment by oravirt** [comment]
Good catch! 
Weird that no-one had run into this earlier. I guess everyone uses lowercase ;-)

**Comment by jschampera** [comment]
Like a charm! Thanks!
