### ISSUE TITLE
oracle_user overwrites profile if not specified

### ISSUE THREAD

**Issue by hkpatv** [oravirt/ansible-oracle-modules#21]
I just tried to use oracle_user to update password.  I did not specify profile, so it defaulted to 'default'.
This had the unexpected side-effect of changing the profile of the user when I only intended to update the password.  
I think default for profile should be None, maybe only resolve default to 'default' if creating user.  Will try to fix myself and submit pull-request.

**Comment by oravirt** [comment]
Hi,

Yes, you are correct. It should be None.  In that case, if it is not set I don't bother checking for the profile when I get the current defaults or try to change it. 
Looks like my tests didnt' cover that possibility ;-)

But just so I understand what happened: You must have had the profile set to something other than 'default', for the user you were updating the password?
I can't see any other option than that as  'default' is the the actual default profile name.

**Comment by hkpatv** [comment]
Yes that is correct, it was set to something other than default
