### ISSUE TITLE
Data type issue in oracle_parameter ?

### ISSUE THREAD

**Issue by ilmarkerm** [oravirt/ansible-oracle-modules#23]
(item={u'scope': u'spfile', u'name': u'compatible', u'value': u'12.1.0.2'}) => {"changed": false, "failed": true, "msg": "Blergh, something went wrong while changing the value - ORA-02017: integer value required\n sql: alter system set compatible = 12.1.0.2 scope=spfile sid='*'", "p": {"name": "compatible", "scope": "spfile", "value": "12.1.0.2"}}

**Comment by oravirt** [comment]
Should be fixed by https://github.com/oravirt/ansible-oracle-modules/commit/6836083e87908ff84b962630828e393a1480b1c8
