### ISSUE TITLE
The variable pdb get the exception

### ISSUE THREAD

**Issue by logikeer** [oravirt/ansible-oracle-modules#38]
in the file oracle_facts:

```
try:
    if database['CDB'] == 'YES':
        pdb = query_result("SELECT con_id, rawtohex(guid) guid_hex, name, open_mode FROM v$pdbs ORDER BY name")
    except:
        pdb = []
```

pdb will get the exception at the function "facts.update"
Maybe we can set the pdb to be [] first

**Comment by ilmarkerm** [comment]
Could you paste the exception here?

**Comment by logikeer** [comment]
`facts.update({'database': database, 'instance': instance, 'rac': rac, 'pdb': pdb, 'tablespace': tablespace, 'temp_tablespace': temp_tablespace, 'userenv': userenv, 'redolog': redolog, 'option': option, 'parameter': parameter})`

because of the pdb is null

I guess the reason is the database['CDB'] != 'YES'....
