### ISSUE TITLE
Support for sysasm

### ISSUE THREAD

**Issue by youssef50** [oravirt/ansible-oracle-modules#48]
How can I get sysasm to work? Thanks

**Comment by oravirt** [comment]
For any specific module?

**Comment by zdevil** [comment]
Hi,

I’m also need some help.
I need it for oracle_sql. 

Appreciate the help!

Thanks

**Comment by oravirt** [comment]
Sure, I'll look into it

**Comment by zdevil** [comment]
Cool, thanks a lot.
