### ISSUE TITLE
Support for authentication with Oracle Wallet

### ISSUE THREAD

**Issue by ilmarkerm** [oravirt/ansible-oracle-modules#6]
Currently modules require specifying hostname/port/servicename+username/password, but they should be able to also authenticate using wallets, then no need to specify passwords in playboks.

**Comment by oravirt** [comment]
Agreed, I've started implementing this.

**Comment by oravirt** [comment]
Fixed as of https://github.com/oravirt/ansible-oracle-modules/commit/3485a78c1feb614d30807923a6f1557b92c8b859
