### ISSUE TITLE
oracle_users password not masked

### ISSUE THREAD

**Issue by topher-debusk** [oravirt/ansible-oracle-modules#62]
I'm using a vaulted password, but it's displaying it in clear text in the log... not sure if there is an easy way around that or not.

```
TASK [oracle_common : | users | create database users] ***************************************************************************************************
skipping: [server1] => (item={u'profile': u'db_mon_profile', u'schema_password': u'Oracle12c', u'authentication_type': u'password', u'state': u'present', u'grants': [u'prtg_role'], u'default_tablespace': u'data', u'schema': u'prtg'})
skipping: [server1] => (item={u'profile': u'db_mon_profile', u'schema_password': u'Oracle12c', u'authentication_type': u'password', u'state': u'present', u'grants': [u'splunk_role'], u'default_tablespace': u'data', u'schema': u'splunk'})
```

**Comment by oravirt** [comment]
Not sure what this is, the passwords are all no_log=True so shouldn’t be visible.

I’m on vacation so have limited possibility to debug this now. Will look when I get the time though.

**Comment by oravirt** [comment]
Just make sure you have the latest changes though

**Comment by topher-debusk** [comment]
it is skipping this section (because the database isn't installed yet 😄)

Maybe that isn't something you can control the output of...

**Comment by oravirt** [comment]
Ok ;-)
You could add `stdout_callback = skippy` in ansible.cfg to not show the skipped task (it only shows the task name)
