### ISSUE TITLE
use tnsnames file for remote connection without wallet

### ISSUE THREAD

**Issue by nalokin** [oravirt/ansible-oracle-modules#74]
Hi,

Is there a way to use tnsnames file without using oracle wallet for remote databases. When hostname is not specified this error is reported as there is no local DB:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not connect to database - ORA-12541: TNS:no listener, connect descriptor: (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=PINGY12)))"}

Thanks!
- N.

**Comment by oravirt** [comment]
How are you running the playbook? Are running the task as '`connection: local`' and trying to connect remotely to the db-server? 
In that case, you could just set `hostname` to the name of the db-server or scan address or something and that will make the sqlnet connection to the remote host.

However, right now it is not possible use a tns alias without a wallet, but I'll look into it.

**Comment by nalokin** [comment]
Thanks for the reply. We've set up direct connections.
