### ISSUE TITLE
oracle_awr should allow for interval of 0 to disable

### ISSUE THREAD

**Issue by topher-debusk** [oravirt/ansible-oracle-modules#76]
Currently we run the following to stop AWR snapshots on our SE instances... I would like to mange this with Ansible instead :)

DBMS_WORKLOAD_REPOSITORY.MODIFY_SNAPSHOT_SETTINGS ( INTERVAL => 0);

It appears the code prevents any values < 10, I would like 0 to be the exception!

Thanks

**Comment by oravirt** [comment]
I've asked @ilmarkerm to look into this as he's the original author of the module

**Comment by ilmarkerm** [comment]
Created a pull request for this

**Comment by topher-debusk** [comment]
thx guys! enjoy your weekend!

**Comment by topher-debusk** [comment]
@ilmarkerm I've tested it and confirmed that it works with 0 - but it shows up as a change each time the playbook is run. When I run the query in query_existing, before I disable AWR, I get the following

`SQL> select c.snap_interval, c.retention from dba_hist_wr_control c join v$database d on c.dbid = d.dbid;

SNAP_INTERVAL                                                               RETENTION
--------------------------------------------------------------------------- ---------------------------------------------------------------------------
+00000 01:00:00.0                                                           +00008 00:00:00.0

1 row selected.
`
Then afterwards
`SQL> select c.snap_interval, c.retention from dba_hist_wr_control c join v$database d on c.dbid = d.dbid;

SNAP_INTERVAL                                                               RETENTION
--------------------------------------------------------------------------- ---------------------------------------------------------------------------
+40150 00:00:00.0                                                           +00008 00:00:00.0

1 row selected.`

**Comment by topher-debusk** [comment]
I'm guessing the 40150 is throwing it off... :(

**Comment by ilmarkerm** [comment]
@topher-debusk I hopefully committed a fix for it now (but not tested)
